alfresco:
  tracker:
    solr:
      url: http://localhost:8983/solr
      collection: alfresco
    repository:
      url: http://localhost:8080/alfresco
      secure-comms: none
    cron:
      metadata: "0/10 * * * * ?"
      acl: "0/10 * * * * ?"
      content: "0/10 * * * * ?"
      commit: "0/20 * * * * ?"
      model: "0/30 * * * * ?"
      cascade: "0/10 * * * * ?"
    batch-count: 5000
    cascade-tracking-enabled: true
    solr-home: /opt/solr/data

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,repairreport
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.alfresco: INFO
    org.apache.solr: WARN
