/*-
 * #%L
 * Search Services E2E Tests
 * %%
 * Copyright (C) 2026 Jeci SARL - https://jeci.fr
 * %%
 * This file is part of the Pristy software, developed by Jeci SARL.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

package org.alfresco.test.search.functional.searchServices.solr.admin;

import io.restassured.RestAssured;
import io.restassured.config.RestAssuredConfig;
import io.restassured.config.SSLConfig;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import org.alfresco.rest.core.RestResponse;

import java.util.HashMap;
import java.util.Map;

/**
 * HTTP client for the tracker admin service's Solr-compat endpoint.
 *
 * <p>For the Pristy https (mTLS) profile the client must present a client certificate.
 * Use the factory method {@link #withMtls(String, String, String, String, String, int)} to
 * obtain a client configured with the PKCS12 keystores generated by
 * {@code keystore/generate-keystores.sh}.</p>
 */
public class TrackerAdminClient
{
    private final String baseUrl;

    /** Optional RestAssured config that carries TLS/mTLS settings. Null = plain HTTP. */
    private final RestAssuredConfig restAssuredConfig;

    /**
     * Creates a plain-HTTP (or basic-HTTPS without client cert) client.
     *
     * @param scheme "http" or "https"
     * @param server hostname or IP of the tracker admin service
     * @param port   port of the tracker admin service (default 8085)
     */
    public TrackerAdminClient(String scheme, String server, int port)
    {
        this.baseUrl = scheme + "://" + server + ":" + port;
        this.restAssuredConfig = null;
    }

    /**
     * Creates an mTLS-capable client that presents a PKCS12 client certificate.
     *
     * @param baseUrl        full base URL including scheme, host and port
     * @param restAssuredConfig pre-built RestAssured config with the SSL settings
     */
    private TrackerAdminClient(String baseUrl, RestAssuredConfig restAssuredConfig)
    {
        this.baseUrl = baseUrl;
        this.restAssuredConfig = restAssuredConfig;
    }

    /**
     * Factory method — creates a client configured for Pristy mTLS.
     *
     * <p>The keystore and truststore must be PKCS12 files produced by
     * {@code STORE_PASS=changeit keystore/generate-keystores.sh <dir>}.
     * Typically {@code trackers.p12} is the client keystore and
     * {@code truststore.p12} is the shared truststore.</p>
     *
     * @param server         hostname or IP (e.g. "trackers" inside Docker, "localhost" from host)
     * @param port           admin port (default 8085)
     * @param keyStorePath   absolute path to the PKCS12 client keystore (e.g. "/keystore/trackers.p12")
     * @param keyStorePass   keystore password (e.g. "changeit")
     * @param trustStorePath absolute path to the PKCS12 truststore (e.g. "/keystore/truststore.p12")
     * @param trustStorePass truststore password (e.g. "changeit")
     * @return a client ready to make mTLS requests to the tracker admin service
     */
    public static TrackerAdminClient withMtls(String server, int port,
            String keyStorePath, String keyStorePass,
            String trustStorePath, String trustStorePass)
    {
        SSLConfig sslConfig = SSLConfig.sslConfig()
                .keyStore(keyStorePath, keyStorePass)
                .trustStore(trustStorePath, trustStorePass);
        RestAssuredConfig config = RestAssured.config().sslConfig(sslConfig);
        String baseUrl = "https://" + server + ":" + port;
        return new TrackerAdminClient(baseUrl, config);
    }

    public RestResponse getAction(String action, String... params)
    {
        Map<String, String> queryParams = new HashMap<>();
        queryParams.put("action", action);
        queryParams.put("wt", "json");

        for (String param : params)
        {
            String[] kv = param.split("=", 2);
            if (kv.length == 2)
            {
                queryParams.put(kv[0], kv[1]);
            }
        }

        RequestSpecification spec = RestAssured.given()
                .baseUri(baseUrl)
                .basePath("/solr/admin")
                .queryParams(queryParams)
                .contentType("application/json");

        if (restAssuredConfig != null)
        {
            spec = spec.config(restAssuredConfig);
        }

        Response response = spec.get("/cores").andReturn();

        return new RestResponse(response);
    }
}
