<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fr.pristy</groupId>
        <artifactId>pristy-search-parent</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>pristy-solr-search-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>Pristy Solr Search parent</name>
    <properties>
        <licenseName>community</licenseName>
    </properties>
    <modules>
        <module>pristy-solrclient-lib</module>
        <module>pristy-indexing-trackers</module>
        <module>pristy-search</module>
        <module>pristy-search-subsystem-solr9</module>
        <module>packaging</module>
    </modules>

    <repositories>
        <repository>
            <id>alfresco-public</id>
            <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>alfresco-public-snapshots</id>
            <url>https://artifacts.alfresco.com/nexus/content/groups/public-snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>maven-restlet</id>
            <name>Public online Restlet repository</name>
            <url>https://maven.restlet.talend.com</url>
        </repository>
    </repositories>
</project>
